package fhir

type Encounter struct {
	ImplicitRules      *Element
	Language           *Element
	PlannedEndDate     *Element
	PlannedStartDate   *Element
	Status             *Element
	Account            []Reference
	ActualPeriod       *Period
	Admission          *EncounterAdmission
	Appointment        []Reference
	BasedOn            []Reference
	BusinessStatus     []EncounterBusinessStatus
	CareTeam           []Reference
	Class              []CodeableConcept
	Contained          []EncounterContainedElem
	Diagnosis          []EncounterDiagnosis
	DietPreference     []CodeableConcept
	EpisodeOfCare      []Reference
	Extension          []Extension
	ID                 *ID
	Identifier         []Identifier
	ImplicitRules_2    *Uri
	Language_2         *Code
	Length             *Duration
	Location           []EncounterLocation
	Meta               *Meta
	ModifierExtension  []Extension
	PartOf             *Reference
	Participant        []EncounterParticipant
	PlannedEndDate_2   *DateTime
	PlannedStartDate_2 *DateTime
	Priority           *CodeableConcept
	Reason             []EncounterReason
	ResourceType       interface{}
	ServiceProvider    *Reference
	ServiceType        []CodeableReference
	SpecialArrangement []CodeableConcept
	SpecialCourtesy    []CodeableConcept
	Status_2           *Code
	Subject            *Reference
	SubjectStatus      *CodeableConcept
	Text               *Narrative
	Type               []CodeableConcept
	VirtualService     []VirtualServiceDetail
}
