package fhir

type Observation struct {
	EffectiveDateTime     *Element
	EffectiveInstant      *Element
	ImplicitRules         *Element
	Issued                *Element
	Language              *Element
	Organizer             *Element
	Status                *Element
	ValueBoolean          *Element
	ValueDateTime         *Element
	ValueInteger          *Element
	ValueString           *Element
	ValueTime             *Element
	BasedOn               []Reference
	BodySite              *CodeableConcept
	BodyStructure         *CodeableReference
	Category              []CodeableConcept
	Code                  CodeableConcept
	Component             []ObservationComponent
	Contained             []ObservationContainedElem
	DataAbsentReason      *CodeableConcept
	DerivedFrom           []Reference
	Device                *Reference
	EffectiveDateTime_2   *string
	EffectiveInstant_2    *string
	EffectivePeriod       *Period
	EffectiveTiming       *Timing
	Encounter             *Reference
	Extension             []Extension
	Focus                 []Reference
	HasMember             []Reference
	ID                    *ID
	Identifier            []Identifier
	ImplicitRules_2       *Uri
	Interpretation        []CodeableConcept
	InterpretationContext []CodeableReference
	Issued_2              *Instant
	Language_2            *Code
	Meta                  *Meta
	Method                *CodeableConcept
	ModifierExtension     []Extension
	Note                  []Annotation
	Organizer_2           *Boolean
	PartOf                []Reference
	Performer             []Reference
	ReferenceRange        []ObservationReferenceRange
	ResourceType          interface{}
	Specimen              *Reference
	Status_2              *Code
	Subject               *Reference
	Text                  *Narrative
	TriggeredBy           []ObservationTriggeredBy
	ValueAttachment       *Attachment
	ValueBoolean_2        *bool
	ValueCodeableConcept  *CodeableConcept
	ValueDateTime_2       *string
	ValueInteger_2        *float64
	ValuePeriod           *Period
	ValueQuantity         *Quantity
	ValueRange            *Range
	ValueRatio            *Ratio
	ValueSampledData      *SampledData
	ValueString_2         *string
	ValueTime_2           *string
}
