// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/auth.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthIntegration_CreatePatient_FullMethodName = "/proto.AuthIntegration/CreatePatient"
)

// AuthIntegrationClient is the client API for AuthIntegration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthIntegrationClient interface {
	CreatePatient(ctx context.Context, in *CreatePatientRequest, opts ...grpc.CallOption) (*CreatePatientResponse, error)
}

type authIntegrationClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthIntegrationClient(cc grpc.ClientConnInterface) AuthIntegrationClient {
	return &authIntegrationClient{cc}
}

func (c *authIntegrationClient) CreatePatient(ctx context.Context, in *CreatePatientRequest, opts ...grpc.CallOption) (*CreatePatientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePatientResponse)
	err := c.cc.Invoke(ctx, AuthIntegration_CreatePatient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthIntegrationServer is the server API for AuthIntegration service.
// All implementations must embed UnimplementedAuthIntegrationServer
// for forward compatibility.
type AuthIntegrationServer interface {
	CreatePatient(context.Context, *CreatePatientRequest) (*CreatePatientResponse, error)
	mustEmbedUnimplementedAuthIntegrationServer()
}

// UnimplementedAuthIntegrationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthIntegrationServer struct{}

func (UnimplementedAuthIntegrationServer) CreatePatient(context.Context, *CreatePatientRequest) (*CreatePatientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePatient not implemented")
}
func (UnimplementedAuthIntegrationServer) mustEmbedUnimplementedAuthIntegrationServer() {}
func (UnimplementedAuthIntegrationServer) testEmbeddedByValue()                         {}

// UnsafeAuthIntegrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthIntegrationServer will
// result in compilation errors.
type UnsafeAuthIntegrationServer interface {
	mustEmbedUnimplementedAuthIntegrationServer()
}

func RegisterAuthIntegrationServer(s grpc.ServiceRegistrar, srv AuthIntegrationServer) {
	// If the following call pancis, it indicates UnimplementedAuthIntegrationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthIntegration_ServiceDesc, srv)
}

func _AuthIntegration_CreatePatient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePatientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthIntegrationServer).CreatePatient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthIntegration_CreatePatient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthIntegrationServer).CreatePatient(ctx, req.(*CreatePatientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthIntegration_ServiceDesc is the grpc.ServiceDesc for AuthIntegration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthIntegration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthIntegration",
	HandlerType: (*AuthIntegrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePatient",
			Handler:    _AuthIntegration_CreatePatient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/auth.proto",
}
