// Code generated by MockGen. DO NOT EDIT.
// Source: access.go
//
// Generated by this command:
//
//	mockgen -source=access.go -destination=access_mocks.go -package=ports TmpAccessClient
//

// Package ports is a generated GoMock package.
package ports

import (
	context "context"
	reflect "reflect"

	domain "github.com/gruzdev-dev/codex-documents/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTmpAccessClient is a mock of TmpAccessClient interface.
type MockTmpAccessClient struct {
	ctrl     *gomock.Controller
	recorder *MockTmpAccessClientMockRecorder
	isgomock struct{}
}

// MockTmpAccessClientMockRecorder is the mock recorder for MockTmpAccessClient.
type MockTmpAccessClientMockRecorder struct {
	mock *MockTmpAccessClient
}

// NewMockTmpAccessClient creates a new mock instance.
func NewMockTmpAccessClient(ctrl *gomock.Controller) *MockTmpAccessClient {
	mock := &MockTmpAccessClient{ctrl: ctrl}
	mock.recorder = &MockTmpAccessClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTmpAccessClient) EXPECT() *MockTmpAccessClientMockRecorder {
	return m.recorder
}

// GenerateTmpToken mocks base method.
func (m *MockTmpAccessClient) GenerateTmpToken(ctx context.Context, data domain.GenerateTmpTokenRequest) (*domain.GenerateTmpTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTmpToken", ctx, data)
	ret0, _ := ret[0].(*domain.GenerateTmpTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTmpToken indicates an expected call of GenerateTmpToken.
func (mr *MockTmpAccessClientMockRecorder) GenerateTmpToken(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTmpToken", reflect.TypeOf((*MockTmpAccessClient)(nil).GenerateTmpToken), ctx, data)
}
