// Code generated by MockGen. DO NOT EDIT.
// Source: document.go
//
// Generated by this command:
//
//	mockgen -source=document.go -destination=document_mocks.go -package=ports DocumentRepository,DocumentService
//

// Package ports is a generated GoMock package.
package ports

import (
	context "context"
	reflect "reflect"

	domain "github.com/gruzdev-dev/codex-documents/core/domain"
	models "github.com/gruzdev-dev/fhir/r5"
	gomock "go.uber.org/mock/gomock"
)

// MockDocumentRepository is a mock of DocumentRepository interface.
type MockDocumentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentRepositoryMockRecorder
	isgomock struct{}
}

// MockDocumentRepositoryMockRecorder is the mock recorder for MockDocumentRepository.
type MockDocumentRepositoryMockRecorder struct {
	mock *MockDocumentRepository
}

// NewMockDocumentRepository creates a new mock instance.
func NewMockDocumentRepository(ctrl *gomock.Controller) *MockDocumentRepository {
	mock := &MockDocumentRepository{ctrl: ctrl}
	mock.recorder = &MockDocumentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentRepository) EXPECT() *MockDocumentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDocumentRepository) Create(ctx context.Context, doc *models.DocumentReference) (*models.DocumentReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, doc)
	ret0, _ := ret[0].(*models.DocumentReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDocumentRepositoryMockRecorder) Create(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDocumentRepository)(nil).Create), ctx, doc)
}

// Delete mocks base method.
func (m *MockDocumentRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDocumentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDocumentRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockDocumentRepository) GetByID(ctx context.Context, id string) (*models.DocumentReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.DocumentReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDocumentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDocumentRepository)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockDocumentRepository) GetByIDs(ctx context.Context, ids []string) ([]models.DocumentReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]models.DocumentReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockDocumentRepositoryMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockDocumentRepository)(nil).GetByIDs), ctx, ids)
}

// Search mocks base method.
func (m *MockDocumentRepository) Search(ctx context.Context, patientID string, limit, offset int) ([]models.DocumentReference, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, patientID, limit, offset)
	ret0, _ := ret[0].([]models.DocumentReference)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockDocumentRepositoryMockRecorder) Search(ctx, patientID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockDocumentRepository)(nil).Search), ctx, patientID, limit, offset)
}

// Update mocks base method.
func (m *MockDocumentRepository) Update(ctx context.Context, doc *models.DocumentReference) (*models.DocumentReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, doc)
	ret0, _ := ret[0].(*models.DocumentReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDocumentRepositoryMockRecorder) Update(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDocumentRepository)(nil).Update), ctx, doc)
}

// MockDocumentService is a mock of DocumentService interface.
type MockDocumentService struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentServiceMockRecorder
	isgomock struct{}
}

// MockDocumentServiceMockRecorder is the mock recorder for MockDocumentService.
type MockDocumentServiceMockRecorder struct {
	mock *MockDocumentService
}

// NewMockDocumentService creates a new mock instance.
func NewMockDocumentService(ctrl *gomock.Controller) *MockDocumentService {
	mock := &MockDocumentService{ctrl: ctrl}
	mock.recorder = &MockDocumentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentService) EXPECT() *MockDocumentServiceMockRecorder {
	return m.recorder
}

// CreateDocument mocks base method.
func (m *MockDocumentService) CreateDocument(ctx context.Context, doc *models.DocumentReference) (*domain.CreateDocumentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDocument", ctx, doc)
	ret0, _ := ret[0].(*domain.CreateDocumentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDocument indicates an expected call of CreateDocument.
func (mr *MockDocumentServiceMockRecorder) CreateDocument(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDocument", reflect.TypeOf((*MockDocumentService)(nil).CreateDocument), ctx, doc)
}

// DeleteDocument mocks base method.
func (m *MockDocumentService) DeleteDocument(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDocument", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDocument indicates an expected call of DeleteDocument.
func (mr *MockDocumentServiceMockRecorder) DeleteDocument(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDocument", reflect.TypeOf((*MockDocumentService)(nil).DeleteDocument), ctx, id)
}

// GetDocument mocks base method.
func (m *MockDocumentService) GetDocument(ctx context.Context, id string) (*models.DocumentReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocument", ctx, id)
	ret0, _ := ret[0].(*models.DocumentReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocument indicates an expected call of GetDocument.
func (mr *MockDocumentServiceMockRecorder) GetDocument(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocument", reflect.TypeOf((*MockDocumentService)(nil).GetDocument), ctx, id)
}

// ListDocuments mocks base method.
func (m *MockDocumentService) ListDocuments(ctx context.Context, patientID string, limit, offset int) (*domain.ListResponse[models.DocumentReference], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDocuments", ctx, patientID, limit, offset)
	ret0, _ := ret[0].(*domain.ListResponse[models.DocumentReference])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDocuments indicates an expected call of ListDocuments.
func (mr *MockDocumentServiceMockRecorder) ListDocuments(ctx, patientID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDocuments", reflect.TypeOf((*MockDocumentService)(nil).ListDocuments), ctx, patientID, limit, offset)
}
