// Code generated by MockGen. DO NOT EDIT.
// Source: files.go
//
// Generated by this command:
//
//	mockgen -source=files.go -destination=files_mocks.go -package=ports FileProvider
//

// Package ports is a generated GoMock package.
package ports

import (
	context "context"
	reflect "reflect"

	domain "github.com/gruzdev-dev/codex-documents/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFileProvider is a mock of FileProvider interface.
type MockFileProvider struct {
	ctrl     *gomock.Controller
	recorder *MockFileProviderMockRecorder
	isgomock struct{}
}

// MockFileProviderMockRecorder is the mock recorder for MockFileProvider.
type MockFileProviderMockRecorder struct {
	mock *MockFileProvider
}

// NewMockFileProvider creates a new mock instance.
func NewMockFileProvider(ctrl *gomock.Controller) *MockFileProvider {
	mock := &MockFileProvider{ctrl: ctrl}
	mock.recorder = &MockFileProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileProvider) EXPECT() *MockFileProviderMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockFileProvider) DeleteFile(ctx context.Context, fileId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, fileId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileProviderMockRecorder) DeleteFile(ctx, fileId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileProvider)(nil).DeleteFile), ctx, fileId)
}

// GetPresignedUrls mocks base method.
func (m *MockFileProvider) GetPresignedUrls(ctx context.Context, data domain.GetPresignedUrlsRequest) (*domain.PresignedUrlsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresignedUrls", ctx, data)
	ret0, _ := ret[0].(*domain.PresignedUrlsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresignedUrls indicates an expected call of GetPresignedUrls.
func (mr *MockFileProviderMockRecorder) GetPresignedUrls(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresignedUrls", reflect.TypeOf((*MockFileProvider)(nil).GetPresignedUrls), ctx, data)
}
