// Code generated by MockGen. DO NOT EDIT.
// Source: observation.go
//
// Generated by this command:
//
//	mockgen -source=observation.go -destination=observation_mocks.go -package=ports ObservationRepository,ObservationService
//

// Package ports is a generated GoMock package.
package ports

import (
	context "context"
	reflect "reflect"

	domain "github.com/gruzdev-dev/codex-documents/core/domain"
	models "github.com/gruzdev-dev/fhir/r5"
	gomock "go.uber.org/mock/gomock"
)

// MockObservationRepository is a mock of ObservationRepository interface.
type MockObservationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockObservationRepositoryMockRecorder
	isgomock struct{}
}

// MockObservationRepositoryMockRecorder is the mock recorder for MockObservationRepository.
type MockObservationRepositoryMockRecorder struct {
	mock *MockObservationRepository
}

// NewMockObservationRepository creates a new mock instance.
func NewMockObservationRepository(ctrl *gomock.Controller) *MockObservationRepository {
	mock := &MockObservationRepository{ctrl: ctrl}
	mock.recorder = &MockObservationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObservationRepository) EXPECT() *MockObservationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockObservationRepository) Create(ctx context.Context, obs *models.Observation) (*models.Observation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, obs)
	ret0, _ := ret[0].(*models.Observation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockObservationRepositoryMockRecorder) Create(ctx, obs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockObservationRepository)(nil).Create), ctx, obs)
}

// Delete mocks base method.
func (m *MockObservationRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockObservationRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockObservationRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockObservationRepository) GetByID(ctx context.Context, id string) (*models.Observation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Observation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockObservationRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockObservationRepository)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockObservationRepository) GetByIDs(ctx context.Context, ids []string) ([]models.Observation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]models.Observation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockObservationRepositoryMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockObservationRepository)(nil).GetByIDs), ctx, ids)
}

// Search mocks base method.
func (m *MockObservationRepository) Search(ctx context.Context, patientID string, limit, offset int) ([]models.Observation, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, patientID, limit, offset)
	ret0, _ := ret[0].([]models.Observation)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockObservationRepositoryMockRecorder) Search(ctx, patientID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockObservationRepository)(nil).Search), ctx, patientID, limit, offset)
}

// Update mocks base method.
func (m *MockObservationRepository) Update(ctx context.Context, obs *models.Observation) (*models.Observation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, obs)
	ret0, _ := ret[0].(*models.Observation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockObservationRepositoryMockRecorder) Update(ctx, obs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockObservationRepository)(nil).Update), ctx, obs)
}

// MockObservationService is a mock of ObservationService interface.
type MockObservationService struct {
	ctrl     *gomock.Controller
	recorder *MockObservationServiceMockRecorder
	isgomock struct{}
}

// MockObservationServiceMockRecorder is the mock recorder for MockObservationService.
type MockObservationServiceMockRecorder struct {
	mock *MockObservationService
}

// NewMockObservationService creates a new mock instance.
func NewMockObservationService(ctrl *gomock.Controller) *MockObservationService {
	mock := &MockObservationService{ctrl: ctrl}
	mock.recorder = &MockObservationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObservationService) EXPECT() *MockObservationServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockObservationService) Create(ctx context.Context, obs *models.Observation) (*models.Observation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, obs)
	ret0, _ := ret[0].(*models.Observation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockObservationServiceMockRecorder) Create(ctx, obs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockObservationService)(nil).Create), ctx, obs)
}

// Delete mocks base method.
func (m *MockObservationService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockObservationServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockObservationService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockObservationService) Get(ctx context.Context, id string) (*models.Observation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*models.Observation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockObservationServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockObservationService)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockObservationService) List(ctx context.Context, patientID string, limit, offset int) (*domain.ListResponse[models.Observation], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, patientID, limit, offset)
	ret0, _ := ret[0].(*domain.ListResponse[models.Observation])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockObservationServiceMockRecorder) List(ctx, patientID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockObservationService)(nil).List), ctx, patientID, limit, offset)
}

// Update mocks base method.
func (m *MockObservationService) Update(ctx context.Context, obs *models.Observation) (*models.Observation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, obs)
	ret0, _ := ret[0].(*models.Observation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockObservationServiceMockRecorder) Update(ctx, obs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockObservationService)(nil).Update), ctx, obs)
}
