// Code generated by MockGen. DO NOT EDIT.
// Source: share.go
//
// Generated by this command:
//
//	mockgen -source=share.go -destination=share_mocks.go -package=ports ShareService
//

// Package ports is a generated GoMock package.
package ports

import (
	context "context"
	reflect "reflect"

	domain "github.com/gruzdev-dev/codex-documents/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockShareService is a mock of ShareService interface.
type MockShareService struct {
	ctrl     *gomock.Controller
	recorder *MockShareServiceMockRecorder
	isgomock struct{}
}

// MockShareServiceMockRecorder is the mock recorder for MockShareService.
type MockShareServiceMockRecorder struct {
	mock *MockShareService
}

// NewMockShareService creates a new mock instance.
func NewMockShareService(ctrl *gomock.Controller) *MockShareService {
	mock := &MockShareService{ctrl: ctrl}
	mock.recorder = &MockShareServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShareService) EXPECT() *MockShareServiceMockRecorder {
	return m.recorder
}

// GetSharedResources mocks base method.
func (m *MockShareService) GetSharedResources(ctx context.Context) (*domain.SharedResourcesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSharedResources", ctx)
	ret0, _ := ret[0].(*domain.SharedResourcesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSharedResources indicates an expected call of GetSharedResources.
func (mr *MockShareServiceMockRecorder) GetSharedResources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharedResources", reflect.TypeOf((*MockShareService)(nil).GetSharedResources), ctx)
}

// Share mocks base method.
func (m *MockShareService) Share(ctx context.Context, req domain.ShareRequest) (*domain.ShareResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Share", ctx, req)
	ret0, _ := ret[0].(*domain.ShareResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Share indicates an expected call of Share.
func (mr *MockShareServiceMockRecorder) Share(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Share", reflect.TypeOf((*MockShareService)(nil).Share), ctx, req)
}
